matrix:
  fast_finish: true
  allow_failures:
  - env: SOLIDITY_COVERAGE=true
  - env: SOLC_NIGHTLY=true
  include:
  - language: node_js
    node_js: "8"
    services:
    - docker
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g npm
    - npm install -g ganache-cli release-it greenkeeper-lockfile
    install:
    - npm install
    before_script:
    - greenkeeper-lockfile-update
    - ganache-cli > ganache-cli.log &
    script:
    - npm run lint
    - npm run test
    - npm run migrate
    - git status
    - git add package-lock.json
    - git diff-index --quiet HEAD || git commit -m "Travis update"
    after_script:
    - greenkeeper-lockfile-upload
  - language: node_js
    node_js: "8"
    env:
    - SOLIDITY_COVERAGE=true
    services:
    - docker
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g npm
    - npm install -g ganache-cli release-it greenkeeper-lockfile
    install:
    - npm install
    before_script:
    - greenkeeper-lockfile-update
    - ganache-cli > ganache-cli.log &
    script:
    - npm run lint
    - npm run test
    - npm run migrate
    - git status
    - git add package-lock.json
    - git diff-index --quiet HEAD || git commit -m "Travis update"
    after_script:
    - greenkeeper-lockfile-upload
  - language: node_js
    node_js: "8"
    env:
    - SOLC_NIGHTLY=true
    services:
    - docker
    cache:
      directories:
      - node_modules
    before_install:
    - npm install -g npm
    - npm install -g ganache-cli release-it greenkeeper-lockfile
    install:
    - npm install
    before_script:
    - greenkeeper-lockfile-update
    - ganache-cli > ganache-cli.log &
    script:
    - npm run lint
    - npm run test
    - npm run migrate
    - git status
    - git add package-lock.json
    - git diff-index --quiet HEAD || git commit -m "Travis update"
    after_script:
    - greenkeeper-lockfile-upload
  - language: python
    python: "3.6"
    install:
    - pip install -r requirements_dev.txt
    - npm install -g npm
    - npm install -g ganache-cli release-it greenkeeper-lockfile
    - npm install
    before_script:
    - greenkeeper-lockfile-update
    - ganache-cli > ganache-cli.log &
    script:
    - npm run migrate
    after_script:
    - greenkeeper-lockfile-upload

notifications:
  email: false

deploy:
  - provider: npm
    email: "devops@oceanprotocol.com"
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true

  - provider: pypi
    distributions: sdist bdist_wheel
    user: ${PYPI_USER}
    password: ${PYPI_PASSWORD}
    on:
      tags: true
      repo: oceanprotocol/keeper-contracts
      python: 3.6

#  - provider: releases
#    api_key: ${GITHUB_OAUTH_TOKEN}
#    skip_cleanup: true
#    on:
#      tags: true
